version: '3.8'

services:
  web:
    container_name: portfolio.osb.im
    image: portfolio.osb.im:1.${BUILD_NUMBER}
    restart: always
    expose:
      - 80
    networks:
      - npm

networks:
  npm:
    external:
      name: npm
